### ISSUE TITLE
Can't build the project.

### ISSUE THREAD

**Issue by jigar-shethia** [argh15/TokenTrend#1]
Seems .xcdatamodeld file is not added in project. 

![Screenshot 2024-04-17 at 3 30 40 PM](https://github.com/argh15/TokenTrend/assets/30865218/a942d1c9-2af9-48ab-81d6-f45a3069b111)
![Screenshot 2024-04-17 at 3 36 19 PM](https://github.com/argh15/TokenTrend/assets/30865218/2e55ee01-b1fe-4b83-be6d-96405e02a6f3)

**Comment by argh15** [comment]
Hi,
The file is already pushed to remote - 
https://github.com/argh15/TokenTrend/blob/master/TokenTrend/Models/PortfolioContainer.xcdatamodeld/PortfolioContainer.xcdatamodel/contents

Can you try to clean and rebuild the project?
